# Generated by Django 5.1.6 on 2025-02-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('ms1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('msx', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ms2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('over2_5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('scores_with_pct', models.JSONField()),
                ('half_scores_with_pct', models.JSONField()),
                ('match_result_with_pct', models.JSONField()),
                ('top_5_first_half', models.TextField()),
                ('top_5_final', models.TextField()),
                ('top3_combo', models.TextField()),
                ('home_team_logo', models.CharField(max_length=100)),
                ('away_team_logo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
