# Generated by Django 5.1.6 on 2025-02-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='away_to_away_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='away_to_away_pct',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='away_to_home_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='away_to_home_pct',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='home_to_away_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='home_to_away_pct',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='home_to_home_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='home_to_home_pct',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
