# Generated by Django 5.1.6 on 2025-02-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_globalteam_transitionmatch_alter_matchresult_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransitionMatch',
            new_name='PastMatches',
        ),
    ]
