# Generated by Django 5.1.6 on 2025-02-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_rename_transitionmatch_pastmatches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalteam',
            old_name='common_name',
            new_name='team_name',
        ),
    ]
