# Generated by Django 5.1.6 on 2025-02-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_rename_common_name_globalteam_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastmatches',
            old_name='away_team_name',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='pastmatches',
            old_name='home_team_name',
            new_name='home_team',
        ),
    ]
