# Generated by Django 5.1.6 on 2025-02-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_rename_away_team_name_pastmatches_away_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalteam',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
