# Generated by Django 5.1.6 on 2025-02-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_globalteam_matches_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='p_3plus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
