# Generated by Django 5.1.6 on 2025-02-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_matchresult_p_3plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pastmatches',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
