# Generated by Django 5.1.6 on 2025-03-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_matchresult_country_pastmatches_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='korner8_5ust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='league',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
