# Generated by Django 5.1.7 on 2025-03-30 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_matchresult_korner8_5ust_alter_matchresult_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='korner8_5ust',
        ),
    ]
