# Generated by Django 4.2.20 on 2025-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_remove_matchresult_korner8_5ust'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='ft_awaygoals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='ft_homegoals',
            field=models.IntegerField(null=True),
        ),
    ]
