# Generated by Django 4.2.20 on 2025-05-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_matchresult_ft_awaygoals_matchresult_ft_homegoals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='ft_awaygoals',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='ft_homegoals',
        ),
    ]
