# Generated by Django 4.2.20 on 2025-05-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_remove_matchresult_ft_awaygoals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='ft_awaygoals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='ft_homegoals',
            field=models.IntegerField(null=True),
        ),
    ]
