# render.yaml
version: "1"

services:
  - type: web
    name: tahmin2        # Render dashboard’daki servis adı
    env: python          # Python ortamı
    plan: starter
    repo: https://github.com/furkanyllmz/tahmin2
    envVars:
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEBUG
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        sync: false
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-post-process --noinput
    startCommand: gunicorn betapp.wsgi:application

cronJobs:                # ← burası camelCase!
  - name: skorupdate
    service: tahmin2      # yukarıdaki service.name ile birebir eşleşmeli
    schedule: "*/30 * * * *"
    command: "python manage.py skorupdate"
