# render.yaml
version: "1"

services:
  - type: web
    name: tahmin2        # Render dashboard’daki servis adı
    env: python          # Python ortamı
    plan: starter
    repo: https://github.com/furkanyllmz/tahmin2
    envVars:
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEBUG
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        sync: false
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-post-process --noinput
    startCommand: gunicorn betapp.wsgi:application
    
  - type: cron
    name: skorupdate-cron        # dilediğin bir isim
    runtime: python
    repo: https://github.com/furkanyllmz/tahmin2
    plan: starter
    region: oregon
    rootDir: ./                  # manage.py’nin olduğu dizin
    schedule: "*/30 * * * *" 
